#!/usr/bin/env ruby

require 'rubygems'
require 'optparse'
require 'net/sftp'

options = {}
OptionParser.new do |opts|
  opts.banner = 'Sftp upload script'

  opts.on('-h', '--host HOST', 'Sftp host') { |host| options[:host] = host }
  opts.on('-u', '--username USERNAME', 'Sftp username') { |username| options[:username] = username }
  opts.on('-p', '--password PASSWORD', 'Sftp password') { |password| options[:password] = password }
end.parse!

src = ARGV.shift
dest = ARGV.shift
dest ||= src

raise 'Host parameter must be provided' if options[:host].nil?
raise 'Username parameter must be provided' if options[:username].nil?
raise 'Path to file must be provided' if src.nil?
raise "File does not exist (#{src})" unless File.file?(src)

Net::SFTP.start(options[:host], options[:username], password: options[:password]) do |sftp|
	sftp.upload!(src, dest)
end

puts "Success: #{src} -> #{dest}"
